name: contextos en actions
run-name: Estamos aprendiendo contextos en actions

on:
  push:
    branches:
      - 'aprendiendo-github-actions'

env:
  nombre: andres

jobs:
  contexto:
    if: ${{ contains(env.nombre, 'andres') }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Correr Script
        run: python main.py

      - name: nombre
        run: echo "${{ env.nombre }} es el nombre actualizado"
