name: expresiones en actions
run-name: Estamos aprendiendo expresiones en actions 4
on: 
  workflow_dispatch:
    inputs:
      nombre: 
        description: 'ponga el nombre'
        required: true
        type: string
  push:
    branches:
      - 'aprendiendo-github-actions'
env:
  nombre: donaldo

jobs:
  contiene:
    runs-on: ubuntu-latest
    if: ${{ contains(env.nombre, 'andres') }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Correr Script
        run: python main.py
      - name: nombre
        run : echo ${{ env.nombre}} es el nombre actualizado

