name: expresiones en actions
run-name: Estamos aprendiendo expresiones en actions 4 
on: 
  push:
    branches:
      - 'aprendiendo-github-actions'
env:
  nombre: andres

jobs:
  contiene:
    runs-on: ubuntu-latest
    if: ${{ contains(env.nombre, 'andres') }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Correr Script
        run: python main.py

