name: expresiones en actions
run-name: Estamos aprendiendo expresiones en actions 3
on:
  workflow_dispatch:
    inputs:
      nombre:
        description: 'pon el nombre'
        required: true
        type: string
        default: 'andres'
  push:
    branches:
      - 'aprendiendo-github-actions'
env:
  nombre: ${{ 'andres' }}

jobs:
  contiene:
    runs-on: ubuntu-latest
    if: ${{contains(inputs.nombre, 'andres') }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Correr Script
        run: python main.py
    
