name: Corriendo Triggers
run-name: Estamos aprendiendo triggers en actions
on: 
  schedule:
    - cron: '25 19 * * *'
  push:
    branches:
      - 'aprendiendo-github-actions'
    paths:
      - '**.py'
  check_suite:
    types: [completed]

jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Correr Script
        run:  python main.py
  
    
    

